### ISSUE TITLE
"Toggle Sidebar" label is positioned incorrectly

### ISSUE THREAD

**Issue by robertbenjamin** [hexpm/hexpm#585]
Stumbled across this here: https://hexdocs.pm/nerves/getting-started.html

<img width="929" alt="screen shot 2017-11-01 at 5 08 52 pm" src="https://user-images.githubusercontent.com/8145721/32303684-5d188f1c-bf27-11e7-9aaa-443a7d9e96a3.png">

The label is a `span` inside a `button`, but doesn't seem to have any styling applied to it.

The vertical spacing can be fixed with the following CSS:

```css
.sidebar-toggle {
  display: flex;
  align-items: center;
}
```

And adding the following fixes the horizontal spacing:

```css
.icon-menu {
  margin-left: 20px;
}
```

Not sure if that's how you guys would like to fix, but wanted to draw attention to it.
